package cn.sz.dra.pojo;
// Generated 2017-3-1 10:42:46 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * News generated by hbm2java
 */
public class News implements java.io.Serializable {

	private Integer nid;
	private Integer ntid;
	private String ntitle;
	private String nauthor;
	private Date ncreatedate;
	private String npicpath;
	private String ncontent;
	private Date nmodifydate;
	private String nsummary;

	public News() {
	}

	public News(Integer ntid, String ntitle, String nauthor, Date ncreatedate, String npicpath, String ncontent,
			Date nmodifydate, String nsummary) {
		this.ntid = ntid;
		this.ntitle = ntitle;
		this.nauthor = nauthor;
		this.ncreatedate = ncreatedate;
		this.npicpath = npicpath;
		this.ncontent = ncontent;
		this.nmodifydate = nmodifydate;
		this.nsummary = nsummary;
	}

	public Integer getNid() {
		return this.nid;
	}

	public void setNid(Integer nid) {
		this.nid = nid;
	}

	public Integer getNtid() {
		return this.ntid;
	}

	public void setNtid(Integer ntid) {
		this.ntid = ntid;
	}

	public String getNtitle() {
		return this.ntitle;
	}

	public void setNtitle(String ntitle) {
		this.ntitle = ntitle;
	}

	public String getNauthor() {
		return this.nauthor;
	}

	public void setNauthor(String nauthor) {
		this.nauthor = nauthor;
	}

	public Date getNcreatedate() {
		return this.ncreatedate;
	}

	public void setNcreatedate(Date ncreatedate) {
		this.ncreatedate = ncreatedate;
	}

	public String getNpicpath() {
		return this.npicpath;
	}

	public void setNpicpath(String npicpath) {
		this.npicpath = npicpath;
	}

	public String getNcontent() {
		return this.ncontent;
	}

	public void setNcontent(String ncontent) {
		this.ncontent = ncontent;
	}

	public Date getNmodifydate() {
		return this.nmodifydate;
	}

	public void setNmodifydate(Date nmodifydate) {
		this.nmodifydate = nmodifydate;
	}

	public String getNsummary() {
		return this.nsummary;
	}

	public void setNsummary(String nsummary) {
		this.nsummary = nsummary;
	}

}
